ioet/time-tracker-ui

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/components/options-sidebar/activities/activities-management/activities-management.component.css
src/app/components/options-sidebar/activities/activities-management/activities-management.component.html
src/app/components/options-sidebar/activities/activities-management/activities-management.component.spec.ts
src/app/components/options-sidebar/activities/activities-management/activities-management.component.ts
src/app/components/options-sidebar/activities/activity-list/activity-list.component.html
src/app/components/options-sidebar/activities/activity-list/activity-list.component.spec.ts
src/app/components/options-sidebar/activities/activity-list/activity-list.component.ts
src/app/components/options-sidebar/activities/create-activity/create-activity.component.html
src/app/components/options-sidebar/activities/create-activity/create-activity.component.spec.ts
src/app/components/options-sidebar/activities/create-activity/create-activity.component.ts
src/app/components/options-sidebar/activities/model/activity.ts
src/app/components/options-sidebar/activities/services/activity.service.spec.ts
src/app/components/options-sidebar/activities/services/activity.service.ts
src/app/components/options-sidebar/project-management/project-management.component.html
src/app/components/shared/create-project/create-project.component.html
src/app/components/shared/project-list/project-list.component.html
src/app/components/shared/sidebar/sidebar.component.html
src/assets/activities.json

This PR has the required code for the **manage activities** screen.

Manage activities screen created

---

package-lock.json
package.json

https://github.com/ioet/time-tracker-ui/issues/39

#39 enforce issue number as part of commit message

---

.prettierrc
README.md
package-lock.json
package.json
src/app/modules/project-management/pages/project-management.component.html
src/app/modules/project-management/pages/project-management.component.ts
src/app/modules/shared/models/entry.model.ts

[Issue 56](https://github.com/ioet/time-tracker-ui/issues/56)
When making a change in the code and saving it in the editor (vscode), it must format the document according to the configured rules

#56 Implement Prettier

---

package-lock.json
package.json

119 fix warning with bootstrap dependency

119 fix warning

---

src/app/modules/activities-management/services/activity.service.ts
src/environments/environment.ts

Removing tenant_id injection on update since this value is going to be injected reading from JWT

fix: #142 fix activities on update

---

src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.html
src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.ts
src/app/modules/shared/components/details-fields/details-fields.component.ts

fix: #252 remove description as required on customers creation

fix: #252 remove description as required on customers creation

---

src/app/modules/time-entries/pages/time-entries.component.html

fix: #275 show time-in out for entries

fix: #275 show time-in out for entries

---

src/app/modules/shared/components/details-fields/details-fields.component.html
src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
src/app/modules/shared/components/details-fields/details-fields.component.ts

fix: #428 show required fields in form

fix: #428 show required fields in form

---

src/app/modules/time-clock/services/entry.service.spec.ts
src/app/modules/time-clock/services/entry.service.ts

Reports page shows all the entries

feat: #460 Showing all rows for reports page

---

src/app/modules/shared/components/technologies/technologies.component.scss

fix: :lipstick: add scroll-snap in technologies component #461

---

src/app/modules/time-clock/services/entry.service.spec.ts
src/app/modules/time-clock/services/entry.service.ts

close #489 
Don't merge this PR yet. Wait for successful merge of https://github.com/ioet/time-tracker-backend/pull/202

feat: :boom: send timezone offset in get time-entries #489

---

package-lock.json

Removing dependency vulnerability

build: #999 Updating dependencies

---

src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
src/app/modules/shared/components/details-fields/details-fields.component.ts

Fix the implementation of future time entry creation

test: #402 Fixing flaky test

---

src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
src/app/modules/time-clock/store/entry.effects.spec.ts
src/app/modules/time-clock/store/entry.effects.ts

feat: :sparkles: preload data of last entry on switching project #503

---

src/app/modules/reports/components/time-range-form/time-range-form.component.html

fix: :iphone: update inputs in reports page #535

---

src/app/modules/reports/components/time-range-form/time-range-form.component.html

Reverts ioet/time-tracker-ui#540

Revert :rewind: "fix: #539 reduce separation on search form"

---

.eslintrc.js
package-lock.json

https://github.com/ioet/time-tracker-ui/issues/549

fix: #549 solve some dependencies issues with problems

---

src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts

feat: :sparkles: Edit start time in Time Clock #233

---

src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts

feat: edit start time in time-clock #233

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/ui-task.md

feat: update issue templates

---

package-lock.json
package.json

This PR resolve some vulnerabilities

TT-80 fix: Fix vulnerability related to ini

---

src/app/modules/users/components/users-list/users-list.component.spec.ts
src/app/modules/users/models/users.ts
src/app/modules/users/store/user.reducer.spec.ts

Remove role field from User model and update the tests.

fix: TT-142 Remove role field from User model

---

README.md

docs: TT-137: Create-Feature Toggles dictionary

---

src/app/modules/shared/components/details-fields/details-fields.component.html
src/app/modules/shared/components/details-fields/details-fields.component.scss

Delete the warning message in the console

fix: TT-165 Warning message in the console

---

src/app/modules/shared/feature-toggles/feature-toggle-general/feature-toggle-general.service.spec.ts
src/app/modules/shared/feature-toggles/feature-toggle-general/feature-toggle-general.service.ts
src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
src/environments/enum.ts

Create a general service for Feature Toggle and reused in different Components.

feat: TT-224 Create a general service for Feature Toggle and its unit tests

---

package-lock.json
package.json

Removing this dependency vulnerability
https://github.com/ioet/time-tracker-ui/security/dependabot/package-lock.json/xmlhttprequest-ssl/open

build: Patching karma to remove transitive dependency vulnerability

---

src/app/modules/time-clock/store/entry.effects.spec.ts
src/app/modules/time-clock/store/entry.effects.ts

Add successful message to updateEntryRunning method and update test of UPDATE_ENTRY_RUNNING message.

feat: TT-234 Add successful message to updateEntryRunning method

---

karma.conf.js
src/app/modules/shared/feature-toggles/filters/feature-filter-provider.service.ts

In this moment we have a problem with random tests.Tests are randomly failing
Currently, a solution that solves this problem has been implemented, however, the root cause of the problem must be found in order to find a more efficient solution.

fix: TT-263 random tests

---

src/app/modules/time-entries/pages/time-entries.component.html
src/app/modules/time-entries/pages/time-entries.component.spec.ts
src/app/modules/time-entries/pages/time-entries.component.ts

Reverts ioet/time-tracker-ui#716

Revert "fix: TT-304 Handle message: the data could not be load"

---

src/app/modules/users/components/users-list/users-list.component.html
src/app/modules/users/components/users-list/users-list.component.ts

Hide test column in users list

feat: TT-471 hide test column in users list

---

src/app/modules/customer-management/components/projects/components/project-list/project-list.component.html
src/app/modules/customer-management/components/projects/components/services/project.service.spec.ts
src/app/modules/customer-management/components/projects/components/services/project.service.ts

This change the visibility of customer's projects

feat: TT-481 change customers project visibility

---

src/app/modules/time-entries/pages/time-entries.component.html
src/app/modules/time-entries/pages/time-entries.component.ts

Modification to fix the pagination error when change month with no data to month with data. Pagination is now keep displaying.

fix: TT-362-pagination-problem-solved

---

.github/workflows/time-tracker-ui-cd-prod.yml
.github/workflows/time-tracker-ui-cd-stage.yml
.github/workflows/time-tracker-ui-ci.yml
infrastructure/main.tf

Migrate remaining Terraform State of the Time Tracker Ui of Azure to AWS

Feat: Devops 202 Migrate remaining tf state time tracker ui

---

.github/workflows/aws-ui-cd-prod.yml
.github/workflows/aws-ui-cd-stage.yml

fix workflow triggers 
cd workflows for stage and  prod

fix: workflow-triggers

---

src/app/modules/shared/components/search-user/search-user.component.html
src/app/modules/shared/components/search-user/search-user.component.ts
src/app/modules/time-clock/services/entry.service.ts

The filter feature on the reports page now supports multiple employees. Other changes were introduced in the backend.
src/app/modules/shared/components/search-user/search-user.component.html
src/app/modules/shared/components/search-user/search-user.component.ts
src/app/modules/time-clock/services/entry.service.ts
- [TTL-908](https://ioetec.atlassian.net/jira/software/c/projects/TTL/boards/61?modal=detail&selectedIssue=TTL-908)
[TTL-908]: https://ioetec.atlassian.net/browse/TTL-908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

TTL-908 modify filter by multiple employees

---

.github/workflows/time-tracker-ui-ci.yml

Erase IaC from the ci pipeline
- github/workflows/time-tracker-ui-ci.yml
- [TTL-926](https://ioetec.atlassian.net/jira/software/c/projects/TTL/boards/61?modal=detail&selectedIssue=TTL-926)
[TTL-926]: https://ioetec.atlassian.net/browse/TTL-926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

refactor: TTL-926 delete iac from ci pipeline
