- README.md
I added the tools that we are using for this project and a little description.
> Add Prerequisites README.md

- src/app/app.module.ts
- src/app/components/options-sidebar/time-clock/time-clock.component.css
- src/app/components/options-sidebar/time-clock/time-clock.component.html
- src/app/components/options-sidebar/time-clock/time-clock.component.spec.ts
- src/app/components/options-sidebar/time-clock/time-clock.component.ts
- src/app/components/shared/details-fields/details-fields.component.css
- src/app/components/shared/details-fields/details-fields.component.html
- src/app/components/shared/details-fields/details-fields.component.spec.ts
- src/app/components/shared/details-fields/details-fields.component.ts
- src/app/components/shared/project-list-hover/project-list-hover.component.css
- src/app/components/shared/project-list-hover/project-list-hover.component.html
- src/app/components/shared/project-list-hover/project-list-hover.component.spec.ts
- src/app/components/shared/project-list-hover/project-list-hover.component.ts
[Issue details](https://github.com/ioet/time-tracker-ui/issues/4)
- When mouse over a project, a clock-in button should appear next to the project name.
- When the clock in button is clicked, show the following fields: Activity, Jira ticket, Technology, and Notes.
- Clock out button should be visible after clock in.
> Add Clock In

- .github/workflows/run_test.yml
Git action allows running test before to do the merge
> add git actions

- src/app/app-routing.module.ts
- src/app/components/options-sidebar/time-clock/time-clock.component.css
- src/app/components/options-sidebar/time-clock/time-clock.component.html
- src/app/components/options-sidebar/time-clock/time-clock.component.spec.ts
- src/app/components/options-sidebar/time-clock/time-clock.component.ts
- src/app/components/shared/clock/clock.component.spec.ts
- src/app/components/shared/clock/clock.component.ts
This PR is related to https://github.com/ioet/time-tracker-ui/issues/9.
The features implemented are:
-When you click on clockIn button, UI display a timer for indicate the time that you work, clockIn change to ClockOut and in the top you can see your entry time.
-When you click on clockOut button, the timer is paused and in the top you can see your exit time. (If the field Technology is empty the user need to enter the information to clockOut).
> Time clock timer component

- src/app/components/shared/user/user.component.css
- src/app/components/shared/user/user.component.html
Removed the bell and help icons and remove some options into the dropdown
Fix the overlapping in dropdown options over navbar.
> remove unnecessary options un navbar

- src/app/components/options-sidebar/time-clock/time-clock.component.spec.ts
> timer component test file

- src/app/app.module.ts
- src/app/modules/project-management/components/project-list/project-list.component.html
- src/app/modules/project-management/components/project-list/project-list.component.spec.ts
- src/app/modules/project-management/components/project-list/project-list.component.ts
- src/app/modules/project-management/pages/project-management.component.spec.ts
- src/app/modules/shared/components/search-project/search-project.component.html
- src/app/modules/shared/components/search-project/search-project.component.spec.ts
- src/app/modules/shared/components/search-project/search-project.component.ts
- src/app/modules/shared/pipes/filter-project/filter-project.pipe.spec.ts
- src/app/modules/shared/pipes/filter-project/filter-project.pipe.ts
- src/app/modules/shared/pipes/index.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.scss
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/assets/project.json
I created a new PR of issue #3.
This PR has the corrections of all the comments previously left.
This branch is clean and explicitly maintains the code for issue #3
> #3 Time Clock - find project

- src/app/modules/activities-management/components/create-activity/create-activity.component.html
- src/app/modules/activities-management/components/create-activity/create-activity.component.ts
- src/app/modules/project-management/components/create-project/create-project.component.html
This PR replaces the previous one.
> 50 improve required field look and feel

- src/app/modules/activities-management/components/activity-list/activity-list.component.scss
- src/app/modules/activities-management/components/activity-list/activity-list.component.ts
- src/app/modules/activities-management/components/create-activity/create-activity.component.spec.ts
- src/app/modules/activities-management/components/create-activity/create-activity.component.ts
- src/app/modules/activities-management/pages/activities-management.component.html
- src/app/modules/activities-management/pages/activities-management.component.spec.ts
- src/app/modules/activities-management/pages/activities-management.component.ts
- src/app/modules/activities-management/services/activity.service.spec.ts
- src/app/modules/activities-management/services/activity.service.ts
- src/app/modules/activities-management/store/activity-management.actions.spec.ts
- src/app/modules/activities-management/store/activity-management.actions.ts
- src/app/modules/activities-management/store/activity-management.effects.ts
- src/app/modules/activities-management/store/activity-management.reducers.spec.ts
- src/app/modules/activities-management/store/activity-management.reducers.ts
- src/app/modules/activities-management/store/activity-management.selectors.ts
- src/app/modules/shared/models/activity.model.ts
this ticket was solved with ngrx
> #44 save activities using API

- src/app/app.module.ts
- src/app/modules/project-management/components/create-project/create-project.component.html
- src/app/modules/project-management/components/create-project/create-project.component.spec.ts
- src/app/modules/project-management/components/create-project/create-project.component.ts
- src/app/modules/project-management/components/project-list/project-list.component.html
- src/app/modules/project-management/components/project-list/project-list.component.spec.ts
- src/app/modules/project-management/components/project-list/project-list.component.ts
- src/app/modules/project-management/pages/project-management.component.html
- src/app/modules/project-management/pages/project-management.component.spec.ts
- src/app/modules/project-management/pages/project-management.component.ts
- src/app/modules/project-management/services/project.service.spec.ts
- src/app/modules/project-management/services/project.service.ts
- src/app/modules/project-management/store/project.actions.spec.ts
- src/app/modules/project-management/store/project.actions.ts
- src/app/modules/project-management/store/project.effects.ts
- src/app/modules/project-management/store/project.reducer.spec.ts
- src/app/modules/project-management/store/project.reducer.ts
- src/app/modules/project-management/store/project.selectors.ts
- src/app/modules/shared/components/modal/modal.component.spec.ts
- src/app/modules/shared/models/project.model.ts
- src/app/modules/shared/pipes/filter-project/filter-project.pipe.spec.ts
- src/app/modules/shared/pipes/filter-project/filter-project.pipe.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.scss
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.ts
- src/app/reducers/index.ts
> #64 get, create and edit projects

- src/app/modules/activities-management/components/activity-list/activity-list.component.ts
- src/app/modules/activities-management/components/create-activity/create-activity.component.ts
- src/app/modules/activities-management/pages/activities-management.component.ts
- src/app/modules/activities-management/services/activity.service.ts
- src/app/modules/activities-management/store/activity-management.reducers.spec.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/reports/pages/reports.component.spec.ts
- src/app/modules/shared/components/clock/clock.component.ts
- src/app/modules/shared/pipes/group-by-date/group-by-date.pipe.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- tslint.json
A new rule was implemented to detect unused variables
> #86 Implement no-unused-variable rule

- src/app/modules/activities-management/components/create-activity/create-activity.component.html
- src/app/modules/login/login.component.html
- src/app/modules/login/login.component.scss
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.scss
- src/scss/_orange-theme.scss
- src/styles.scss
- src/styles/themes/_orange-theme.scss
Adding styles for login screen
Setting default values for buttons
> #71 adding styles for login screen

- README.md
Update README with the required instructions after integrating stryker
> #112 update README

- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.ts
#85 reading activities with api
> #85 reading activities with api

- src/styles/themes/_orange-theme.scss
> fix: #78 remove border in buttons

- .github/workflows/CD-time-tracker-ui.yml
- .github/workflows/CI-mutation-tests.yml
- .github/workflows/CI-time-tracker-ui.yml
- README.md
- scripts/populate-keys.sh
- src/app/app.module.ts
- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.scss
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/components/modal/modal.component.spec.ts
- src/app/modules/shared/models/entry.model.ts
- src/app/modules/shared/models/index.ts
- src/app/modules/shared/models/technology.model.ts
- src/app/modules/shared/services/technology.service.spec.ts
- src/app/modules/shared/services/technology.service.ts
- src/app/modules/shared/store/technology.actions.spec.ts
- src/app/modules/shared/store/technology.actions.ts
- src/app/modules/shared/store/technology.effects.ts
- src/app/modules/shared/store/technology.reducers.spec.ts
- src/app/modules/shared/store/technology.reducers.ts
- src/app/modules/shared/store/technology.selectors.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- src/app/reducers/index.ts
- src/environments/environment.ts
- src/environments/keys.ts
[Issue #29](https://github.com/ioet/time-tracker-ui/issues/29)
- Get Technologies from StackExchange API
> #29 Get Technologies

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.scss
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.scss
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
[Issue #114](https://github.com/ioet/time-tracker-ui/issues/114)
- Refactor project list grid on time-clock option
> fix: #114 Refactor project list grid

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
[Issue #37](https://github.com/ioet/time-tracker-ui/issues/137)
Hide the technology list by clicking outside it
> fix: #137 Fix the technology list

- src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.spec.ts
- src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.ts
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.spec.ts
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.ts
- src/app/modules/customer-management/services/customer.service.ts
- src/app/modules/customer-management/store/customer-management.actions.spec.ts
- src/app/modules/customer-management/store/customer-management.actions.ts
- src/app/modules/customer-management/store/customer-management.effects.ts
- src/app/modules/customer-management/store/customer-management.reducers.spec.ts
- src/app/modules/customer-management/store/customer-management.reducers.ts
- src/app/modules/customer-management/store/customer-management.selectors.ts
- src/environments/environment.ts
> Read customers from api

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.scss
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.scss
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.ts
[Issue 145](https://github.com/ioet/time-tracker-ui/issues/145)
Use details-fields component on the Time Clock page
> fix: #145 use details-fields component on Time Clock page

- src/app/app.module.ts
- src/app/modules/shared/interceptors/inject.token.interceptor.spec.ts
- src/app/modules/shared/interceptors/inject.token.interceptor.ts
Add Authorization header using the token from session storage.
> fix: #148 adding interceptor to inject Authorization headers

- src/app/app.module.ts
- src/app/modules/shared/models/entry.model.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.actions.spec.ts
- src/app/modules/time-clock/store/entry.actions.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-clock/store/entry.reducer.spec.ts
- src/app/modules/time-clock/store/entry.reducer.ts
- src/app/reducers/index.ts
[Issue 146](https://github.com/ioet/time-tracker-ui/issues/146)
- Create new time-entries
> fix: #146 Create new time entry

- src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.html
- src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.ts
#186 mark customer description
#185 fix error message
> Mark description as required

- .github/workflows/CI-mutation-tests.yml
- .github/workflows/CI-time-tracker-ui.yml
- package-lock.json
- src/app/app.module.ts
- src/app/modules/shared/models/entry.model.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.scss
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.actions.spec.ts
- src/app/modules/time-clock/store/entry.actions.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-clock/store/entry.reducer.spec.ts
- src/app/modules/time-clock/store/entry.reducer.ts
- src/app/modules/time-clock/store/entry.selectors.ts
[Issue 150](https://github.com/ioet/time-tracker-ui/issues/150)
- Get active entry
- Update active entry
> fix: #150 Get active entry and update entry

- src/app/modules/activities-management/components/activity-list/activity-list.component.spec.ts
- src/app/modules/shared/components/modal/modal.component.html
- src/app/modules/shared/components/modal/modal.component.spec.ts
- src/app/modules/shared/components/modal/modal.component.ts
- src/app/modules/shared/models/entry.model.ts
- src/app/modules/shared/store/technology.effects.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.ts
- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.actions.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-clock/store/entry.reducer.spec.ts
- src/app/modules/time-clock/store/entry.reducer.ts
- src/app/modules/time-clock/store/entry.selectors.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
> Clock out functionality

- src/app/modules/activities-management/store/activity-management.reducers.ts
- src/app/modules/activities-management/store/activity-management.selectors.spec.ts
- src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.spec.ts
- src/app/modules/customer-management/components/projects-type/components/project-type-list/project-type-list.component.spec.ts
- src/app/modules/customer-management/services/customer.service.spec.ts
- src/app/modules/customer-management/store/customer-management.actions.spec.ts
- src/app/modules/customer-management/store/customer-management.reducers.spec.ts
- src/app/modules/shared/models/customer.model.ts
- src/app/modules/time-clock/store/entry.selectors.ts
fix: #191 Adding tests for some code with no tests
> fix: #191 Adding tests for some code with no tests

- src/app/app.module.ts
- src/app/modules/activities-management/pages/activities-management.component.html
- src/app/modules/activities-management/pages/activities-management.component.spec.ts
- src/app/modules/activities-management/pages/activities-management.component.ts
- src/app/modules/shared/components/notification/notification/notification.component.html
- src/app/modules/shared/components/notification/notification/notification.component.spec.ts
- src/app/modules/shared/components/notification/notification/notification.component.ts
I created a notification component to reuse this code.
I'm working with type action to define the msg, I'm not using the message property define in the ActivityState interface.
> fix: #169 Display message after saving/deleting activities

- src/app/modules/activities-management/pages/activities-management.component.spec.ts
- src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.ts
- src/app/modules/customer-management/components/projects/components/create-project/create-project.component.spec.ts
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.spec.ts
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.ts
- src/app/modules/customer-management/components/projects/components/services/project.service.ts
- src/app/modules/customer-management/components/projects/components/store/project.actions.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.actions.ts
- src/app/modules/customer-management/components/projects/components/store/project.effects.ts
- src/app/modules/customer-management/components/projects/components/store/project.reducer.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.reducer.ts
- src/app/modules/customer-management/components/projects/components/store/project.selectors.ts
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
Time-clock should display all existing projects to end-users.
> Show all projects on time-clock screen

- src/app/modules/shared/messages.ts
- src/app/modules/time-clock/pages/time-clock.component.ts
- src/app/modules/time-clock/store/entry.effects.ts
- Moving some messages to effects
- Removing message each time an entry is updated
- Creating a shared class to hold messages to be used by the `toastrService`
> 242 remove message on entry updated

- src/app/modules/activities-management/store/activity-management.effects.ts
- src/app/modules/customer-management/components/projects-type/store/project-type.effects.ts
- src/app/modules/customer-management/components/projects/components/store/project.effects.ts
- src/app/modules/customer-management/store/customer-management.effects.ts
- src/app/modules/shared/store/technology.effects.ts
- src/app/modules/time-clock/store/entry.effects.ts
254 display error messages from backend
> 254 display error messages from backend

- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
fix: #273 no default project selected on time-clock
> fix: #273 no default project selected on time-clock

- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.html
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.scss
Removing pagination from table
Other features to the table were not added since it seems unnecessary to have filtering and searching in tables with few raws
> fix: #297 removing pagination from table

- src/app/app-routing.module.ts
- src/app/guards/admin-guard/admin-guard.ts
- src/app/guards/admin-guard/admin.guard.spec.ts
- src/app/guards/login-guard/login.guard.spec.ts
- src/app/guards/login-guard/login.guard.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/login/services/azure.ad.b2c.service.ts
- src/app/modules/shared/components/sidebar/sidebar.component.spec.ts
- src/app/modules/shared/components/sidebar/sidebar.component.ts
fix: #205 adding checks to restrict access for admin and non-admin users
> fix: #205 adding checks to restrict access for admin and non-admin users

- src/app/app.module.ts
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.scss
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.spec.ts
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/app/modules/reports/components/time-range-form/time-range-form.component.html
- src/app/modules/reports/components/time-range-form/time-range-form.component.ts
- src/app/modules/reports/components/time-range-form/time-range.component.spec.ts
- src/app/modules/reports/pages/reports.component.html
- src/app/modules/reports/pages/reports.component.spec.ts
- src/app/modules/shared/components/input-date/input-date.component.html
- src/app/modules/shared/components/input-date/input-date.component.scss
- src/app/modules/shared/components/input-date/input-date.component.spec.ts
- src/app/modules/shared/components/input-date/input-date.component.ts
- src/app/modules/shared/components/input-label/input-label.component.html
- src/app/modules/shared/components/input-label/input-label.component.scss
- src/app/modules/shared/components/input-label/input-label.component.spec.ts
- src/app/modules/shared/components/input-label/input-label.component.ts
- src/app/modules/time-clock/models/time-entries-time-range.ts
- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.actions.spec.ts
- src/app/modules/time-clock/store/entry.actions.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-clock/store/entry.reducer.spec.ts
- src/app/modules/time-clock/store/entry.reducer.ts
- src/app/modules/time-clock/store/entry.selectors.spec.ts
- src/app/modules/time-clock/store/entry.selectors.ts
- src/styles/colors.scss
- Adding the time entries report page.
- Fixing some errors on code.
- Refactoring some unit tests ( Removing duplicated code)
- Removing false positive tests
- Improving coverage on unit tests ( Now some @effects are tested)
> 204 reports page

- src/app/modules/activities-management/components/activity-list/activity-list.component.html
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.html
- src/app/modules/customer-management/components/projects-type/components/project-type-list/project-type-list.component.html
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.scss
- src/app/modules/reports/components/time-range-form/time-range-form.component.html
- src/app/modules/reports/pages/reports.component.html
- src/app/modules/reports/pages/reports.component.spec.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.html
- src/styles/colors.scss
Improving the look and feel on the report page so that it can be displayed on medium and low-resolution screens.
> feat: #310 Improving css on the report page

- src/app/modules/reports/components/time-range-form/time-range-form.component.ts
- src/app/modules/reports/components/time-range-form/time-range.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/models/time-entries-time-range.ts
- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.reducer.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
closes #329 reload entries after clock-in
closes #274 sets the right project id on time-clock screen
closes #327 modal is closed after updating the information
closes #325 adds a wildcard to query the entries report
closes #323 sets the activity to blank on time-clock screen
> Fix some issues

- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.spec.ts
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/login/services/azure.ad.b2c.service.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
> 309 Removing flaky tests

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.ts
fix: #328 removing cleaning data from form
> fix: #328 removing cleaning data from form

- src/app/modules/shared/components/sidebar/models/item-sidebar.model.ts
- src/app/modules/shared/components/sidebar/sidebar.component.html
- src/app/modules/shared/components/sidebar/sidebar.component.scss
- src/app/modules/shared/components/sidebar/sidebar.component.spec.ts
- src/app/modules/shared/components/sidebar/sidebar.component.ts
Highlighting the selected menu option.
> feat: #279 Highlighting selected menu option

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/models/entry.model.ts
- src/app/modules/time-clock/pipes/time-details.pipe.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- Allow edit entry running
- Enabling notifications when updating time entries
- Refreshing data when creating/updating time entries
> 333 allow edit entry running

- src/app/modules/reports/components/time-range-form/time-range-form.component.ts
- src/app/modules/reports/components/time-range-form/time-range.component.spec.ts
- src/app/modules/time-clock/models/time-entries-time-range.ts
- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.actions.spec.ts
- src/app/modules/time-clock/store/entry.actions.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-clock/store/entry.reducer.spec.ts
This PR fixes how the data for reports is queried. Now the start date begins at `00:00` and the end date finish at `23:59`.
> 346 fixing report time

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.scss
Fixing width columns for the report's table.
> fix: #365 Fixing the report's column widths

- src/app/modules/reports/components/time-range-form/time-range-form.component.html
- src/app/modules/reports/components/time-range-form/time-range-form.component.ts
- src/app/modules/reports/components/time-range-form/time-range.component.spec.ts
fix: #347 pre-fill start end dates in report
> fix: #347 pre-fill start end dates in report

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/store/entry.reducer.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
> fix: #368 clean form after saving data and closes #377

- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
> fix: :alien: add time_offset query param to summary endpoint

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/components/details-fields/save-entry-event.ts
- src/app/modules/shared/models/entry.model.ts
- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.actions.spec.ts
- src/app/modules/time-clock/store/entry.actions.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
Allow users to restart a time entry.
> Allowing users to restart time entries

- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
> set seconds to zero on create time-entry #399

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
closes #423 sets current date to avoid issues updating data of running entry
closes #414 errors trying to update entry
closes #434 enhance report file name
> fix: #414 fix time in stop

- src/app/modules/time-clock/components/time-entries-summary/time-entries-summary.component.ts
> fix: update summary each minute

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/components/month-picker/month-picker.component.html
- src/app/modules/shared/components/month-picker/month-picker.component.scss
- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
Highlighting selected menu on time entries section
> 315 highlight selected month

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.scss
- src/styles.scss
Improve styles on the project component
- Alignments
- Paddings
- Colors
> 413 Improving styles on the project component

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
It updates the Date format on the report page.
Now dates are displayed following this pattern: `MM/dd/yyyy`
**Note** The number of rows displayed should be checked in the backend side since it is limiting the amount of data sent to the frontend
> feat: #447 Updating the date format on the report page

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/models/entry.model.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
> :construction: Send timezone_offset when time_entries are being created/updated

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/shared/models/entry.model.ts
Please don't merge this PR before this PR is merged and deployed https://github.com/ioet/time-tracker-backend/pull/197
> fix: #453 include customer and project id in reports

- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
> fix: :bug: refresh active entry on edit actions #481

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.scss
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/app/modules/reports/components/time-range-form/time-range-form.component.html
* Reducing font size
* Removing some columns from UI
* Moving Search button so that it can be displayed on low-resolution screens
> feat: #418 Improve reports table

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/components/details-fields/project-selected-event.ts
- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
> feat: :sparkles: preload data on create entry #490

- .github/workflows/CD-time-tracker-ui.yml
- .github/workflows/CI-mutation-tests.yml
- .github/workflows/CI-time-tracker-ui.yml
- README.md
- package-lock.json
- package.json
- scripts/populate-keys.sh
- src/app/guards/admin-guard/admin.guard.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggles.service.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggles.service.ts
- src/app/modules/shared/feature-toggles/toggle.model.ts
- src/environments/environment.ts
- src/environments/keys.example.ts
Adding support for feature flags on UI
> Adding support for feature flags on UI

- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/components/time-entries-summary/time-entries-summary.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
> fix: :iphone: make summary elements responsive #527

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.scss
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.scss
> fix: :iphone: improve forms of time-entries page

- src/app/modules/activities-management/components/activity-list/activity-list.component.scss
- src/app/modules/activities-management/components/create-activity/create-activity.component.html
- src/app/modules/activities-management/pages/activities-management.component.html
- src/app/modules/time-clock/pages/time-clock.component.html
- src/app/modules/time-clock/pages/time-clock.component.scss
> fix: make responsive forms of activities section #537

- src/app/modules/reports/components/time-range-form/time-range-form.component.html
https://github.com/ioet/time-tracker-ui/issues/539
> fix: #539 reduce separation on search form

- src/app/modules/shared/components/sidebar/sidebar.component.html
- src/app/modules/shared/components/sidebar/sidebar.component.scss
> fix: make autocomplete take full height #544

- src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
Reverts ioet/time-tracker-ui#552
> Revert "feat: :sparkles: Edit start time in Time Clock #233"

- src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
> fix: #560 select input on click

- src/app/modules/activities-management/components/activity-list/activity-list.component.html
- src/app/modules/customer-management/components/customer-info/components/create-customer/create-customer.html
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.html
- src/app/modules/customer-management/components/projects-type/components/project-type-list/project-type-list.component.html
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.html
Show read-only GUID field in customers and project sections.
Close #562
> feat: #562 Show read only GUID field

- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.spec.ts
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.ts
- src/app/modules/customer-management/components/projects-type/components/create-project-type/create-project-type.component.spec.ts
- src/app/modules/customer-management/components/projects-type/components/create-project-type/create-project-type.component.ts
- src/app/modules/customer-management/components/projects/components/create-project/create-project.component.spec.ts
- src/app/modules/customer-management/components/projects/components/create-project/create-project.component.ts
Fix bug that cannot create a project, after modifying a project of a different customer.
> fix: #563 fix bug cannot creat project

- src/app/modules/activities-management/store/activity-management.effects.spec.ts
- src/app/modules/activities-management/store/activity-management.selectors.spec.ts
- src/app/modules/customer-management/components/projects-type/store/project-type.effects.spec.ts
- src/app/modules/customer-management/components/projects-type/store/project-type.selectors.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.effects.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.selectors.spec.ts
- src/app/modules/customer-management/store/customer-management.effects.spec.ts
- src/app/modules/customer-management/store/customer-management.selectors.spec.ts
- src/app/modules/shared/store/technology.effects.spec.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.selectors.spec.ts
Test creation for the missing effects and selectors files to improve the coverage.
> test: #576 add test to effects files and selectors

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/modules/shared/components/sidebar/sidebar.component.spec.ts
- src/app/modules/shared/components/sidebar/sidebar.component.ts
- src/app/modules/users/components/users-list/users-list.component.html
- src/app/modules/users/components/users-list/users-list.component.spec.ts
- src/app/modules/users/components/users-list/users-list.component.ts
- src/app/modules/users/models/users.ts
- src/app/modules/users/pages/users.component.html
- src/app/modules/users/pages/users.component.spec.ts
- src/app/modules/users/pages/users.component.ts
- src/app/modules/users/services/users.service.spec.ts
- src/app/modules/users/services/users.service.ts
- src/app/modules/users/store/index.ts
- src/app/modules/users/store/user.actions.spec.ts
- src/app/modules/users/store/user.actions.ts
- src/app/modules/users/store/user.effects.spec.ts
- src/app/modules/users/store/user.effects.ts
- src/app/modules/users/store/user.reducer.spec.ts
- src/app/modules/users/store/user.reducers.ts
- src/app/modules/users/store/user.selectors.spec.ts
- src/app/modules/users/store/user.selectors.ts
- src/app/reducers/index.ts
A feature that inserts a new option to the administrator role to see the users.
> 569 create option users

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
> feat: #566 Datepicker for departure date in entry form

- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/users/store/user.actions.ts
- src/app/modules/users/store/user.reducer.spec.ts
function to change the start and end time of previous time entry when switch project
> fix: #572 allow manual editing in time in when switch project

- package.json
- src/app/app.module.ts
- src/app/guards/login-guard/login.guard.spec.ts
- src/app/guards/login-guard/login.guard.ts
- src/app/modules/login/login.component.spec.ts
- src/app/modules/login/login.component.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/login/services/azure.ad.b2c.service.ts
Manage user session in the browser to avoid logging in to the app again
> TT-15 keep the user logged in

- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
This PR is the 1st part of the task, the 2nd part is in the backend
> TT-69 Overlap Hours

- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/store/entry.actions.spec.ts
- src/app/modules/time-clock/store/entry.actions.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-clock/store/entry.reducer.spec.ts
- src/app/modules/time-clock/store/entry.reducer.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
Fix bug when is updating two entries in order
> TT-70 fix: fix bug when update two entries

- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/store/entry.effects.ts
With these changes, we ensure that at the moment the time-entry is created, the technologies field is set as an empty list. See TT-64 for details.
> TT-64 fix: set technologies as list when create time-entry

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
fix a bug that not allow to update changes on "time entries".
> TT-85 fix: fix overlapping seconds on time entries

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
There is a test missing. Looking at some documentation we need something else (Test/Wrapper Component) to test the whole feature of the 'goingToWorkOnThis'. This could be done in tech debt :(. Not a clean solution, but regarding time, it's enough.
> TT-52 fix: date out takes date in when goingToWorkOnThis is false

- src/app/modules/shared/components/month-picker/month-picker.component.html
- src/app/modules/shared/components/month-picker/month-picker.component.scss
- src/app/modules/shared/components/month-picker/month-picker.component.spec.ts
- src/app/modules/shared/components/month-picker/month-picker.component.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.actions.ts
- src/app/modules/time-clock/store/entry.effects.ts
- src/app/modules/time-clock/store/entry.reducer.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- tslint.json
> TT-39 fix: comments

- src/app/modules/shared/components/month-picker/month-picker.component.html
- src/app/modules/shared/components/month-picker/month-picker.component.scss
- src/app/modules/shared/components/month-picker/month-picker.component.spec.ts
- src/app/modules/shared/components/month-picker/month-picker.component.ts
https://user-images.githubusercontent.com/12575632/103682550-0afc7b80-4f57-11eb-91cf-75ee1b9d5990.mov
> TT-107 feat: Limit the year selector in UI to the current year

- src/app/modules/users/components/users-list/users-list.component.spec.ts
- src/app/modules/users/models/users.ts
Add a user Roles field in the model User
> TT-111 fix: Add a roles field in Users

- src/app/modules/users/components/users-list/users-list.component.html
- src/app/modules/users/components/users-list/users-list.component.spec.ts
- src/app/modules/users/components/users-list/users-list.component.ts
Remove Feature Toggles from User List
* **note:**
* With This change, the flaky test will disappear.
> fix: TT-132 Remove Feature Toggle from User list

- src/app/modules/users/components/users-list/users-list.component.html
The table users is responsive for mobile screens
> fix: TT-138 The table users does not adapt to mobile screens

- src/app/modules/users/components/users-list/users-list.component.spec.ts
- src/app/modules/users/components/users-list/users-list.component.ts
Fix the bug when grant and revoke actions are dispatched and there's a glitch of actions.
> fix: TT-143 Add a loadUsers action after grant or revoke user role

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.scss
- src/app/modules/shared/components/details-fields/details-fields.component.ts
It is necessary to choose project to enter the data
> fix: TT-140 time entry info is lost if project is selected at last

- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.ts
Resolve exponential growth of requests in TimeClock, ProjectListHover and EntryFields components.
> TT-106 exponential growth UI

- src/app/modules/activities-management/components/activity-list/activity-list.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.scss
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/app/modules/reports/components/time-range-form/time-range-form.component.html
- src/app/modules/time-entries/pages/time-entries.component.ts
> fix: TT-144 Responsive all tables

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
feature to update the date out when editing the date in.
> fix: TT 149 when edit date in update the date out

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
disable future dates on date in and date out
> fix: TT-167 Date picker disable future dates

- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
Add the parameters startDate and endDate in the path used by the findEntriesByProjectId method of the EntryService service.
> fix: TT-168 Add the parameters startDate and endDate in the path

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
add @angular/cdk and a unit test
> feat: TT-35 make new entries creation modal panel draggable

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.scss
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.spec.ts
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
make uri clickable when possible
> fix: TT-178 Make URI clickable when possible

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-entries/pages/time-entries.component.html
Add form reset icon in (timeEntries)
> fix: TT-23 Clear form when adding an entry (Time Entries)

- src/app/modules/shared/components/sidebar/sidebar.component.spec.ts
- src/app/modules/shared/components/sidebar/sidebar.component.ts
Using FT I added an implementation in sidebar component and corresponding unit tests
> feat: TT-191 Validate the new flow for permission management

- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
Add FT in EntryFieldsComponent component to get  the new changes, add the flag to validate the current entry and last entry, add tests of the Feature Toggle - update-entries.
> feat: TT-217 Add FT in EntryFieldsComponent component and Add flag at validate current entry and last entry

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.scss
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/environments/environment.ts
Calculate time difference when new entries added
> fix: TT 20 calculate time difference when new entries added

- angular.json
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.scss
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/styles.scss
> TT 205 in safari browser dont work the date picker

- src/app/modules/activities-management/components/activity-list/activity-list.component.html
- src/app/modules/activities-management/components/activity-list/activity-list.component.spec.ts
- src/app/modules/activities-management/components/activity-list/activity-list.component.ts
- src/app/modules/activities-management/store/activity-management.actions.spec.ts
- src/app/modules/activities-management/store/activity-management.actions.ts
- src/app/modules/activities-management/store/activity-management.effects.spec.ts
- src/app/modules/activities-management/store/activity-management.effects.ts
- src/app/modules/activities-management/store/activity-management.reducers.spec.ts
- src/app/modules/activities-management/store/activity-management.reducers.ts
- src/app/modules/activities-management/store/activity-management.selectors.spec.ts
- src/app/modules/activities-management/store/activity-management.selectors.ts
- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/models/activity.model.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-entries/pages/time-entries.component.html
A UI implementation was made to perform archiving and activation activities. The UI currently looks like this.
> TT-208 don't allow deleting activities

- src/app/modules/reports/components/time-range-form/time-range-form.component.ts
- src/app/modules/shared/components/input-date/input-date.component.html
- src/app/modules/shared/components/input-date/input-date.component.spec.ts
- src/app/modules/shared/components/input-date/input-date.component.ts
> fix: TT-230 implement datepicker safari on Reports

- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.html
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.spec.ts
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.ts
- src/app/modules/customer-management/components/projects/components/store/project.actions.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.actions.ts
- src/app/modules/customer-management/components/projects/components/store/project.effects.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.effects.ts
- src/app/modules/customer-management/components/projects/components/store/project.reducer.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.reducer.ts
- src/app/modules/customer-management/components/projects/components/store/project.selectors.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.selectors.ts
- src/app/modules/shared/models/project.model.ts
Projects can be archived or activated
> Tt 218 dont allow deleting projects

- src/app/modules/shared/pipes/substract-date/substract-date.pipe.spec.ts
- src/app/modules/shared/pipes/substract-date/substract-date.pipe.ts
I have refactored the logic of the difference presentation and corrected the bug
> TT-38 Fix pipe to calculate difference between time-out and time-in

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
We found a bug when changing the value of the `goingToWorkOnThis` variable in `ngOnChanges`, it was setting a value to undefined because the object being checked did not have the property at the time of adding a new time entry. We fixed the error using "Nullish coalescing operator" in addition to correcting the bug mentioned in the ticket.
> TT-236 When you add a new entry and check "I'm working on this" you should take the current time for "Time in"

- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.html
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.spec.ts
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.ts
Hi Team, I solved the problem by creating a new method to show the project type in the table. The problem is solved and the project type is displaying in the project-list table in the customers-management.
> fix: TT-24 Display project type in projects table

- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.spec.ts
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.ts
This pull request solves the problem "TypeError: Cannot read property 'map' of undefined" that some pull request were haveing while CI/CD process
> fix: Test Cannot read property 'map' of undefined.

- src/app/modules/login/login.component.spec.ts
- src/app/modules/login/login.component.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/login/services/azure.ad.b2c.service.ts
- src/app/modules/shared/feature-toggles/feature-toggle-cookies/feature-toggle-cookies.service.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggle-cookies/feature-toggle-cookies.service.ts
- src/app/modules/shared/feature-toggles/feature-toggle-general/feature-toggle-general.service.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggle-general/feature-toggle-general.service.ts
- src/app/modules/shared/feature-toggles/feature-toggle-manager.service.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggle-manager.service.ts
- src/app/modules/shared/feature-toggles/feature-toggle-provider.service.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggle-provider.service.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/environments/enum.ts
I solved the task with:
- Add function getAllFeatureToggle() : This method gets all the FeatureToggle of the Azure Endpoint. The Endpoint returns an object of type PagedAsyncIterableIterator, so we use for await to iterate. 
- Add function getAllFeatureToggleEnableForUser() : This method gets all the FeatureToggle from the provider to filter them and return only the Feature Toggle where the user is. 
- Add method getActivated(): This method returns all FeatureToggles enable for user. It use's getAllFeatureToggleEnableForUser() from FeatureManagerService.
- Create  FeatureToggleCookiesService: This services stores all of the user's toggle features in cookies
- Modify all components that it use´s feature toggle: Now, when the component want to know if any feature toggle are enable for the …
> feat: TT-19 Create Cookies of FeatureToggle

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
add canMarkEntryAsWIP in some conditions.
> TT-255 When I have an entry running, I cannot add new entries.

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/models/project.model.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
Currently the Backend response from the endpoint:
```bash
<time-tracker-backend-url>/projects/<project-id>
```
has the following structure: 
```json
{
"customer_name": "JAND, Inc., DBA Warby Parker",
"customer": {
"name": "JAND, Inc., DBA Warby Parker",
"description": ""
},
"project_type": {
"name": "QA",
"description": "Projects in which most work is creating and/or running test or setting up test infrastructure."
},
...
},
```
In the future `customer_name` field will be removed, now we have to access the customer name through `customer` field like
```ts
project.customer.name
```
With this pull request this Behavior has been achieved.
> TT-259 Validate call to new customer structure on project

- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
fix: TT-91 The time out of the penultimate time entry overlaps the time entry that is running
Added a condtion to save the entry in time-entries component and the problem is solved.
> fix: TT-91 Time out of the penultimate entry overlaps the entry that is running

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/models/entry.model.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
**### Problem:**
There is an error when adding a new entry select a project and click on the check **"I am working on this"**, the dashboard shows the time in "00:00".
**### Solutions:** 
In the method **projectSelected** the variable star_date sets the time in how 00:00, this is a data burned. We need to change the data.
> fix: TT-258 Click on the check I am working on this

- src/app/modules/activities-management/store/activity-management.effects.spec.ts
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.html
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.spec.ts
- src/app/modules/customer-management/components/projects/components/project-list/project-list.component.ts
- src/app/modules/customer-management/store/customer-management.effects.spec.ts
- src/app/modules/customer-management/store/customer-management.effects.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/user/services/user-info.service.spec.ts
- src/app/modules/user/services/user.service.spec.ts
- src/app/modules/user/services/user.service.ts
In this PR, I **added** some unit testing in the methods that were not tested, and  I **removed** the unit testing that was unnecessary in the project.
> TT-264 UI test coverage

- src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
If somebody added a new time entry and if in the DB not existing register about of the information the attribute activity_id. The application can not show the information about time entry and the reports, and return: the data can not be loaded. 
When the user selects a new project, in the panel time clock, to default send an activity_id, and the DB.
> fix: TT-282 added conditions in method onSubmit and added array of activities in component project-list-hover

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
Cannot read property 'clientWidth', this problem present in the section of Reports.
We added a new "Subscription" variable and its respective unsubscribe routine.
> Tt 286 handle error message client width

- package.json
- src/app/app.module.ts
- src/app/modules/shared/components/month-picker/month-picker.component.spec.ts
- src/app/modules/shared/components/month-picker/month-picker.component.ts
- src/app/modules/shared/pipes/substract-date/substract-date.pipe.spec.ts
- src/app/modules/shared/pipes/substract-date/substract-date.pipe.ts
- src/app/modules/time-entries/components/calendar/calendar.component.html
- src/app/modules/time-entries/components/calendar/calendar.component.scss
- src/app/modules/time-entries/components/calendar/calendar.component.spec.ts
- src/app/modules/time-entries/components/calendar/calendar.component.ts
- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- src/environments/enum.ts
- src/styles.scss
- src/styles/colors.scss
A new feature has been added that allows you to view time entries in a calendar.
**Month View:** 
**Week View:**
**Day View**:
To add this new feature:
- We created a feature toggle to wrap the new feature
- We added an external module called "Angular Calendar"
- We have added a method for get the time difference in minutes within SubstractDatePipe
- We have modified MonthPickerComponent so that the date can be updated from outside the component.
> Tt 279 angular calendar implementation

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
An additional comparison was added in order to allow the user to change the date of an entry. Because of that, certain tests were removed because they were no longer relevant. However, the method that was modified has other tests relevant for what it actually does.
To summarize, one method was modified, two tests were removed because no longer needed.
> Tt 289 cannot edit the date of an entry

- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/feature-toggles/feature-toggle-general/feature-toggle-general.service.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/environments/enum.ts
**Problem**
Currently, there are some unnecessary feature toggles in the UI.
**Solution**
Removed feature toggles and the unit testing associated.
> refactor: TT-295 removal unnecessary feature toggles

- src/app/modules/activities-management/store/activity-management.reducers.spec.ts
- src/app/modules/activities-management/store/activity-management.reducers.ts
In the UI, when archiving or unarchiving an activity, all the content of it was shown on the UI, as shown in the picture below. This was not visually comfortable for the user, and thus the content does not need to appear when performing the actions mentioned at the beginning.
The variables which were causing this visual problem were removed and therefore, the tests needed for those variables are no longer necessary and were also removed.
> Tt 299 activities when active inactive an activity not display information in name description

- src/app/modules/time-entries/components/calendar/calendar.component.html
- src/app/modules/time-entries/components/calendar/calendar.component.scss
- src/app/modules/time-entries/components/calendar/calendar.component.spec.ts
- src/app/modules/time-entries/components/calendar/calendar.component.ts
Currently in the part of the calendar that is merged into production, when clicking on the week or day view, these views show entries from 12 AM and users have to scroll to the current time or task they are working on.  
This PR solves this problem by making the week and day views display at the current time or to be more specific to show the view in the red horizontal bar.
> feat: TT-296 add scroll to the current time in calendar component

- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
**Problem**
------------
In the time-entries section, when there is no data, the message _"The data could not be load"_ is displayed.
**Solution**
------------
When there is no data, the message _"The data could not be load"_ must not be displayed, instead the message _"No data available in table"_ should be displayed in the table section. That is the purpose of this pull request.
> fix: TT-304 Handle message: the data could not be load

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
Currently there is an error with some entries that does not allow to modify their start or end time, the error that is generated is the following:
When attempting to modify the following entries:
This error occurs because in the current implementation to modify the entries they are not taking into account the seconds of the entries, in other words, only hours and minutes are taken into account.
With this PR, this implementation has been fixed and now takes into account all the information of the start/end time of the entry.
> fix: TT-311 Can not update entries fixed

- src/app/modules/users/components/users-list/users-list.component.html
- src/app/modules/users/components/users-list/users-list.component.spec.ts
- src/app/modules/users/components/users-list/users-list.component.ts
- src/app/modules/users/store/user.actions.spec.ts
- src/app/modules/users/store/user.actions.ts
- src/app/modules/users/store/user.effects.spec.ts
- src/app/modules/users/store/user.effects.ts
- src/app/modules/users/store/user.reducers.spec.ts
- src/app/modules/users/store/user.reducers.ts
- src/environments/environment.ts
Currently, the backend verifies the user has the `admin` role to visualize information in the reports section.
However, the Time Tracker UI, in the Users section, only adds the user to the group of `time-tracker-admin` but does not add the role.
With this PR each time a user is added to the admin group, the admin role is also added, and if the user is removed, the admin role is removed as well.
> fix: TT-310 Reports do not work with groups fixed

- package.json
It would be better if we run unit tests before commiting, and only commit and push after tests are successful.
To do so, on the package.json file it was needed just to modify the husky configuration as follows:
```
"husky": {
"hooks": {
"commit-msg": "commit-message-validator",
"pre-commit": "ng lint && ng test --watch=false --browsers=ChromeHeadless"
}
}
```
> fix: TT-313 run unit tests before commiting

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/utils/project-storage.util.spec.ts
- src/app/modules/shared/utils/project-storage.util.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.html
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- src/environments/environment.ts
Currently there is the functionality to store recent projects in the LocalStorage, this feature works correctly, however, it does not keep an update with the data that exists on the server, that is, if a project/customer is deactivated and if the person had it saved in the LocalStorage of his browser, he will still have it available and will be able to mark entries with that project, even though the project/customer has already been deactivated.
With this PR a synchronization is established between the user's projects in the LocalStorage and the projects returned by the server. For example, if the user has a project in the LocalStorage that has been disabled, it will be removed since it does not exist in the server.
> feat: TT-314 Synchronize local projects with Server projects

- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
In the time-entries section, when there is no data, the message "The data could not be load" is displayed.
When there is no data, instead of the message "The data could not be load", the message "No data available in table" should be displayed in the table section. That is the purpose of this pull request.
> TT-304 Handle message: the data could not be load

- src/app/modules/shared/utils/project-storage.util.ts
Currently there is the functionality to store recent projects in the LocalStorage, this feature works correctly, however, it does not keep an update with the data that exists on the server, that is, if a project/customer is deactivated and if the person had it saved in the LocalStorage of his browser, he will still have it available and will be able to mark entries with that project, even though the project/customer has already been deactivated.
With this PR a synchronization is established between the user's projects in the LocalStorage and the projects returned by the server. For example, if the user has a project in the LocalStorage that has been disabled, it will be removed since it does not exist in the server.
> fix: TT-314 Synchronize local storage projects

- angular.json
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/components/technologies/technologies.component.html
- src/app/modules/shared/components/technologies/technologies.component.spec.ts
- src/app/modules/shared/components/technologies/technologies.component.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.html
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
Currently the component to choose Technologies does not have such a nice user experience, it does not allow to use the keyboard arrows to select technologies.
It was decided to replace the entire component and use `ng-select` library, resulting in a much more attractive component with a better user experience. as shown in the following image:
> feat: TT-18 autocomplete component for entering technologies

- src/app/modules/time-entries/components/calendar/calendar.component.html
- src/app/modules/time-entries/components/calendar/calendar.component.scss
- src/app/modules/time-entries/components/calendar/calendar.component.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- src/styles.scss
As Time-tracker is working now, there are a few problems with the calendar feature in the Time entries section.
The problems are:
**1.- In the month view, when we scroll down, the days of the week disappear:**
**2.- The same problem described above occurs in the week view section:**
**3.- Also, in the month view, when we decrease the size of the screen, the time entries are not responsive:**
For the problems listed before, the solutions are:
**1.- In this pull request, no matter how deep we scroll in the calendar, the days of the week stay fixed as a header:**
**2.- The solution in the previous point also applies to the week section:**
**3.- In terms of the time entries, when there is a reduction in the screen size, time entries decrease its size as well:**
**Note:**
**As a bonus in this …
> style: TT-315 Fixed headers days of the week

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/users/components/users-list/users-list.component.html
1. In the Users section, there is a table with the following columns: User email, Names, and Groups. This is not so useful, because the names of the users should go first:
2. In the Reports section, the Duration column is not showing all its letters, it seems like there is a problem with the name of the column:
1. A switch between the Email column and the Names column has been made to improve the user experience:
2. The Duration column now is showing all its letters:
> style: TT-320 Improve customers and users tables

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/time-entries/pages/time-entries.component.html
The user experience in the create/edit input modal was improved, more intuitive icons and a button to drag the modal has been added, the result is as follows:
> feat: TT-321 Improve create/edit Entry modal

- src/app/modules/time-entries/components/calendar/calendar.component.spec.ts
Currently there is an error with a test, which only fails at the end of the month. The test that fails is as follows:
This test has been corrected so that it does not fail again on these dates.
> fix: TT-325 Fix wrong Test in calendar component

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/styles.scss
In the Reports section, when we select the "Column visibility" button, this button shows a button row where each button represents a column name in the table.
This is working fine, but there is no notable difference between the selected buttons and no selected buttons inside this button row.
Moreover, when there is a reduction in the screen size, the "Column visibility" button is not showing anything.
In this pull request when we select the "Column visibility" button, we can see a clear difference between the selected buttons and no selected buttons by their color.
Also, when the screen size changes, the "Column visibility" button will display the button row as it normally does, adding a scroll in the y-axis.
**Note:**
**As a bonus, the print button functionality was improved, now it only …
> Tt 318 improve column visibility section

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
Currently in the Reports section, when the CSV or Excel buttons are selected, these do not show the ID columns in the exported file.
The previous functionality of the buttons was implemented.
> fix: TT-333 Fix functionality of Excel and CSV buttons

- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
With the modification of the lines of code of this pull request, each new time entry created from the "Time Entries" menu will have the following hour format established: "HH:mm:ss", where ss will always be set to 00 to avoid conflicts with inexistent time overlaps.
> fix: TT-328 when editing/creating entries set seconds to 0

- src/app/modules/shared/components/sidebar/sidebar.component.ts
The project sidebar presents some elements, depending on the group to which the user belongs, and a style is applied to the element (option) when it is selected. However, when the page is reloaded, the selected option is not presented with the active style.
When the page is reloaded, a comparison is made between the selected option and the route where it is located, to add the active style to the selected option in the sidebar.
> fix: TT-334 Keep the sidebar item selected when the page is refreshed

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/modules/shared/components/dark-mode/dark-mode.component.html
- src/app/modules/shared/components/dark-mode/dark-mode.component.spec.ts
- src/app/modules/shared/components/dark-mode/dark-mode.component.ts
- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/sidebar/sidebar.component.html
- src/app/modules/shared/components/sidebar/sidebar.component.scss
- src/app/modules/shared/components/sidebar/sidebar.component.ts
- src/assets/icons/moon.svg
- src/assets/icons/sun.svg
- src/environments/enum.ts
- src/styles.scss
- tailwind.config.js
The dark mode is a temporary change in the color palette of the software, this feature offers several benefits, among the main ones are: it prevents the user's vision from getting tired in less time and battery-saving due to the reduction of the screen brightness. 
Using Tailwind CSS to style Time Tracker UI in dark mode, allowing the user to switch between light and dark mode. Also, Tailwind was configured to set the color palette for the project.
> feat: TT-332 Dark mode 

- src/app/modules/shared/components/sidebar/sidebar.component.scss
- src/styles.scss
At the moment, the UI does not allow us to use the whole screen, there is a problem at the bottom of the page, so we have content shrinked, as in the following picture:
[![](https://i.postimg.cc/B6TbKTrR/Screenshot-from-2021-09-16-17-32-10.png)](https://i.postimg.cc/B6TbKTrR/Screenshot-from-2021-09-16-17-32-10.png)
Styling files were modified, so we can have an improved user experience in the UI. The result is as in the following picture, where you can see that the content is using the whole screen now:
[![](https://i.postimg.cc/5yf0qH1y/Screenshot-from-2021-09-16-17-33-32.png)](https://i.postimg.cc/5yf0qH1y/Screenshot-from-2021-09-16-17-33-32.png)
> fix: TT-340 remove unwanted space at the bottom of the UI

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.spec.ts
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
The Duration column format inside the Reports section is not correct. This format is presenting the data in hours and minutes.
This pull request retrieves the previous format of the Duration column. This format displays the data in hours or multiples of hours.
> fix: TT-336 Fix format Duration column

- src/app/modules/activities-management/components/activity-list/activity-list.component.ts
- src/app/modules/activities-management/components/create-activity/create-activity.component.html
- src/app/modules/activities-management/components/create-activity/create-activity.component.spec.ts
- src/app/modules/activities-management/components/create-activity/create-activity.component.ts
- src/app/modules/activities-management/pages/activities-management.component.html
- src/app/modules/activities-management/pages/activities-management.component.spec.ts
- src/app/modules/activities-management/pages/activities-management.component.ts
When the "Add a new activity" button is clicked, it should reset the "Name" and "Description" fields.
This pull request implements the reset form fields function on the "Add new activity" button.
> TT-354 fix bug in Add new activity button

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- src/styles.scss
Pagination option was added to **Time entries** and **Reports** tabs, where it was not previously available. Also, test for new methods were created.
> Tt 344 add pagination where feature is not available

- src/app/modules/time-entries/pages/time-entries.component.html
We're using the initial version of dataTable 1.10.22, this version resolve problems with pagination.
> fix: TT-364 remove duplicated message not data available

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.spec.ts
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
**Objetive:**
Exclude from reports this tags in the Ticket column
```
<a_ngcontent-vlm-c151=' class="is-url"> https://ioetec.atlassian.net/k
"ng-reflect-ng-if": "true"
1->
```
The problem is solved by removing these tags with a regular expression.
With the solution it looks like this:
> fix: TT-392 format correct to column Time and export reports exclude tags < />

- src/app/modules/activities-management/components/activity-list/activity-list.component.html
- src/app/modules/activities-management/pages/activities-management.component.html
**Problem**
The activity view needs to be read-only to retrieve this information from json.
**Solution**
Hidden the modify and create buttons inside the activity view.
> feat: TT-395 remove button create, update and dropdown

- src/app/modules/shared/components/dark-mode/dark-mode.component.ts
**Problem**
Console error "ERROR TypeError: Cannot read properties of undefined (reading 'enabled')"
**Solution**
the dark mode component file was modified to fix the console error validating when you do not have the dark mode permissions
> fix: TT-428 solution bug console error dark mode

- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/components/technologies/technologies.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
**Problem**
Whenever a user enters in the Time Clock>Projects, they have to type in a project for the feature to show a message.
the message of the technologies is not clear and new users do not understand how it works
**Solution**
when it is a new user, all available projects are displayed and when it is an old user, only the old projects are displayed.
improved help text of technologi
> fix: TT-413 show projects when you do not have the latest projects

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.ts
**Problem**
Whenever a user records a time entry, user has to record the date in and date out.
**Solution**
when the user enters a new time entry he can only enter the entry date and the exit date will be updated automatically.
> fix: TT-437 validated maximum time entry hours

- src/app/modules/activities-management/components/activity-list/activity-list.component.html
- src/app/modules/activities-management/pages/activities-management.component.ts
Corrected status column doesn't showed in production
> feat: TT-430 read activities in localhost

- src/app/modules/activities-management/components/activity-list/activity-list.component.html
Column status label corrected in development mode
> fix: TT-430 status column showed

- src/app/modules/shared/components/details-fields/details-fields.component.ts
Problem
checkbox "I am working on this" is always marked
Solution
checkbox is an optional functionality
> fix: TT-457 solution bug Checkbox "I am working on this"

- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
Create a new time-entry from time-clock functionality
> feat: TT-443 Use V2 for start timeEntry from timeClock

- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
This reverts commit ae78b6a5c56acd26b1b790791e9358c0b8405b19.
> Revert "feat: TT-443 Use V2 for start timeEntry from timeClock (#777)"

- src/app/modules/users/components/users-list/users-list.component.html
This fix the disposition of the test column in production like follows:
Before:
After:
> fix: TT-471 fix the disposition of column test

- package.json
- src/app/app.module.ts
- src/app/guards/login-guard/login.guard.spec.ts
- src/app/guards/login-guard/login.guard.ts
- src/app/modules/home/home.component.spec.ts
- src/app/modules/home/home.component.ts
- src/app/modules/login/login.component.html
- src/app/modules/login/login.component.spec.ts
- src/app/modules/login/login.component.ts
- src/app/modules/login/services/login.service.spec.ts
- src/app/modules/login/services/login.service.ts
- src/app/modules/shared/components/dark-mode/dark-mode.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/sidebar/sidebar.component.spec.ts
- src/app/modules/shared/components/sidebar/sidebar.component.ts
- src/app/modules/shared/components/user/user.component.spec.ts
- src/app/modules/shared/components/user/user.component.ts
- src/app/modules/shared/feature-toggles/feature-toggle-cookies/feature-toggle-cookies.service.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggle-general/feature-toggle-general.service.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggle-manager.service.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggle-provider.service.spec.ts
- src/app/modules/shared/feature-toggles/filters/feature-filter-provider.service.spec.ts
- src/app/modules/shared/feature-toggles/filters/feature-filter-provider.service.ts
- src/app/modules/shared/interceptors/inject.token.interceptor.spec.ts
- src/app/modules/shared/interceptors/inject.token.interceptor.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.ts
- src/environments/enum.ts
this Pr is for config the login with google locally
> feat: TT-453 add Authentication with google locally

- src/app/modules/shared/components/details-fields/details-fields.component.html
Resolve the bug "the project isn't shown when edit time entries"
> fix: TT-486 the project isn't shown when edit time entries

- src/app/modules/users/components/users-list/users-list.component.html
- src/app/modules/users/services/users.service.spec.ts
- src/app/modules/users/services/users.service.ts
Routes for granting and revoking admin role to users were changed in order to consume the new endpoints from the backend v2. The switch button is working now.
> fix: TT-483 consume new endpoint from be v2

- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.html
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.spec.ts
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.ts
- src/app/modules/customer-management/store/customer-management.actions.spec.ts
- src/app/modules/customer-management/store/customer-management.actions.ts
- src/app/modules/customer-management/store/customer-management.effects.ts
- src/app/modules/customer-management/store/customer-management.reducers.spec.ts
The change of status is calling now to the update instead of the delete.
> fix: TT-477 customer change status

- src/app/modules/customer-management/components/projects-type/components/create-project-type/create-project-type.component.ts
Validate the field description in project_types when we create a new project type.
> fix: TT-504 Review create Project type

- src/app/modules/shared/components/details-fields/details-fields.component.html
Reverts ioet/time-tracker-ui#791
> Revert "fix: TT-482 input Date out change disable to false"

- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-clock/services/entry.service.ts
In this PR the endpoint created for reports is used. In production it will not change the route.
Working in local
Working in production
> Tt 501 integrate reports with the new backend

- src/app/modules/activities-management/store/activity-management.actions.ts
- src/app/modules/activities-management/store/activity-management.reducers.spec.ts
- src/app/modules/customer-management/components/management-customer-projects/management-customer-projects.component.spec.ts
- src/app/modules/customer-management/components/projects-type/components/project-type-list/project-type-list.component.spec.ts
- src/app/modules/customer-management/components/projects-type/store/project-type.reducers.spec.ts
- src/app/modules/customer-management/components/projects/components/services/project.service.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.actions.ts
- src/app/modules/customer-management/components/projects/components/store/project.reducer.spec.ts
- src/app/modules/customer-management/store/customer-management.actions.ts
- src/app/modules/customer-management/store/customer-management.reducers.spec.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/input-date/input-date.component.spec.ts
- src/app/modules/shared/feature-toggles/feature-toggles.service.spec.ts
- src/app/modules/shared/store/technology.actions.ts
- src/app/modules/shared/store/technology.reducers.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.reducer.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- src/app/modules/user/store/user.actions.ts
- src/app/modules/user/store/user.reducer.spec.ts
- src/app/modules/users/store/user.reducers.spec.ts
Unit test coverage is complete. Currently the coverage is 99.35%.
> test: TT-281 UI Test Coverage Second Part

- src/app/modules/login/services/login.service.spec.ts
- src/app/modules/login/services/login.service.ts
- src/app/modules/shared/components/user/user.component.html
- src/app/modules/shared/components/user/user.component.scss
- src/app/modules/shared/components/user/user.component.ts
Reverts ioet/time-tracker-ui#825
> Revert "feat: TT-577 get profile pic from Google account"

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.ts
- src/styles/colors.scss
> TT-579 Improve reports screen

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.scss
Reverts ioet/time-tracker-ui#846
> Revert "Tt 37 show complete descriptions on hover"

- README.md
To show how to run the UI in dev and prod mode in the two ways (using and without using Docker)
> TTA-91-refactor-time-tracker-ui-readme-md

- src/app/modules/login/login.component.ts
- src/app/modules/shared/interceptors/inject.token.interceptor.ts
The purpose of this Pull Request is to redirect the user when his access token expires.
**How?**
I merged the logic that was used in legacy. We subscribe to the login service, and it will unsubscribe if we try to make a request with an expired token. Also, in the token injector HTTP interceptor, I added a pipe that checks if the response is 401 unauthorized. If it is, it will redirect the user to the login page.
**Files changed**
- Login component.ts for the logic mentioned above.
- inject.token.interceptor.ts
- Some files that were failing on the linting.
> fix: TTA-209 add subscription to login component for redirecting user

- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- Test manually calendar view feature toogle in order to relase the feature to all users.
- Remove feature toogle flags.
- src/app/modules/time-entries/pages/time-entries.component.html
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.ts
- [TTL-815](https://ioetec.atlassian.net/browse/TTL-815)
- Given time tracker ui when time entries page load then Calendar view button appear on the upper right side
- Given Calendar view when click on a time entry then a modal to eddit time entry appear
- Given Calendar view when click on remove button then a modal to confirm appear
- Given Calendar view when click on week view then you can see the time entries per week
- Given Calendar view when click on day view then you can …
> feat: TTL-815-test-calendar-view-feature-toggle

- .github/workflows/CD-time-tracker-ui.yml
- .github/workflows/CI-mutation-tests.yml
- .github/workflows/CI-time-tracker-ui.yml
Since we changed our infrastructure, we have CI/CD pipelines that achieve the goals that we want right now. The pipelines deactivated in this PR are the legacy ones, and we don't need them anymore.
> [TTL-746] Deactivate Legacy Pipelines

- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.html
Customer table is not working fine, sometimes (randomly) shows as it doesn't have data but it has.
Using async pipe multiple times can cause problems because we’re doing multiple subscriptions and that’s the reason why it works randomly.
Is not necessary to use it two times. We just need to remove one of them.
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.html
- [TTL-795](https://ioetec.atlassian.net/browse/TTL-795)
Given customer table when the page loads then the table is filled correctly
[TTL-795]: https://ioetec.atlassian.net/browse/TTL-795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: TTL-795-fix-customers-table-remove-duplicated-subscription

- .github/workflows/time-tracker-ui-ci.yml
- src/app/modules/customer-management/components/projects/components/services/project.service.spec.ts
- src/app/modules/customer-management/components/projects/components/store/project.effects.spec.ts
- src/app/modules/shared/interceptors/inject.token.interceptor.spec.ts
- src/app/modules/time-clock/services/entry.service.spec.ts
- src/app/modules/time-entries/pages/time-entries.component.spec.ts
Discard 2 deprecated tests, fixed others for the new backend.
- M       src/app/modules/customer-management/components/projects/components/services/project.service.spec.ts
- M       src/app/modules/customer-management/components/projects/components/store/project.effects.spec.ts
- M       src/app/modules/shared/interceptors/inject.token.interceptor.spec.ts
- M       src/app/modules/time-clock/services/entry.service.spec.ts
- M       src/app/modules/time-entries/pages/time-entries.component.spec.ts
> fix: tests

- package.json
- src/app/app-routing.module.ts
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.ts
- src/app/modules/login/login.component.ts
- src/app/modules/shared/components/sidebar/sidebar.component.ts
- src/app/modules/shared/interceptors/inject.token.interceptor.ts
- src/app/modules/shared/pipes/substract-date-return-float/substract-date-return-float.pipe.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- Change "Time Clock" section, to "Home" (however, path remains the same)
- Lint changes
- Commit message validator changes from TTA- to TTL-
- package.json
- src/app/app-routing.module.ts
- src/app/modules/customer-management/components/customer-info/components/customer-list/customer-list.component.ts
- src/app/modules/login/login.component.ts
- src/app/modules/shared/components/sidebar/sidebar.component.ts
- src/app/modules/shared/interceptors/inject.token.interceptor.ts
- src/app/modules/shared/pipes/substract-date-return-float/substract-date-return-float.pipe.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- 
- [Change "Time Clock" page name](https://ioetec.atlassian.net/jira/software/c/projects/TTL/boards/61?modal=detail&selectedIssue=TTL-784)
> Ttl 784 change time clock page name

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/reports/components/time-entries-table/time-entries-table.component.spec.ts
- src/app/modules/shared/models/entry.model.ts
A new column named time zone was added to show the local time where the time entry was created.
- Add a list of files that have been changed:
src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
src/app/modules/reports/components/time-entries-table/time-entries-table.component.spec.ts
src/app/modules/shared/models/entry.model.ts
- [TTL 886](https://ioetec.atlassian.net/jira/software/c/projects/TTL/boards/61?modal=detail&selectedIssue=TTL-886)
> TTL 886 display time zone reports

- src/app/modules/shared/services/technology.service.spec.ts
- src/app/modules/shared/services/technology.service.ts
Allow special characters when searching for technology.
- src/app/modules/shared/services/technology.service.ts
- [Technology not found for special caracter](https://ioetec.atlassian.net/browse/TTL-888)
> fix: TTL-888 special characters searching tech

- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/shared/internal-app-constants.ts
- src/app/modules/shared/messages.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/time-clock/pages/time-clock.component.ts
Add validation when saving time entries of internal projects. They must have a description or a ticket name(uri).
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- src/app/modules/shared/messages.ts
- src/app/modules/shared/internal-app-constants.ts
- [Internal Apps required](https://ioetec.atlassian.net/browse/TTL-887)
> 887 validate required fields for internal apps

- src/app/modules/time-entries/pages/time-entries.component.html
Display times according to current user timezone_offset, in Time Entries page, in order for the user to be able to create time entries clearly seeing that they do not overlap.
src/app/modules/time-entries/pages/time-entries.component.html
- [address Dylan's bug regarding time zones](https://ioetec.atlassian.net/jira/software/c/projects/TTL/boards/61?modal=detail&selectedIssue=TTL-866)
- create time entries
- see the time entries in the Time Entries section
- Change the time zone in your PC, refresh the page, and see how the displayed times change
- Change the time offset in the entries (editing the DB) and see the displayed times DO NOT change
> refactor: TTL-866 display times according to current user timezone_offset

- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
Prevent home page from sending the form when required fields are missing.
Fix existing tests.
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.spec.ts
- src/app/modules/time-clock/components/entry-fields/entry-fields.component.ts
- [TTL-898](https://ioetec.atlassian.net/jira/software/c/projects/TTL/boards/61?selectedIssue=TTL-898)
Should not let time entries be saved by updating time in, or technologies in the home pages if required fields are not filled.
[TTL-898]: https://ioetec.atlassian.net/browse/TTL-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ttl 898 fix bug that lets you save without required fields

- src/app/modules/activities-management/pages/activities-management.component.spec.ts
- src/app/modules/activities-management/store/activity-management.selectors.spec.ts
- src/app/modules/customer-management/components/management-customer-projects/management-customer-projects.component.spec.ts
- src/app/modules/customer-management/store/customer-management.actions.spec.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/reports/components/time-range-custom/time-range-header/time-range-header.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/search/search.component.spec.ts
- src/app/modules/shared/components/technologies/technologies.component.spec.ts
- src/app/modules/shared/formatters/number.formatter.spec.ts
- src/app/modules/shared/store/technology.actions.spec.ts
- src/app/modules/time-clock/pages/time-clock.component.spec.ts
- src/app/modules/time-entries/components/calendar/calendar.component.spec.ts
- src/app/modules/users/store/user.selectors.spec.ts
Debug test log errors
Fix 1 tests 
- src/app/modules/activities-management/pages/activities-management.component.spec.ts
- src/app/modules/activities-management/store/activity-management.selectors.spec.ts
- src/app/modules/customer-management/components/management-customer-projects/management-customer-projects.component.spec.ts
- src/app/modules/customer-management/store/customer-management.actions.spec.ts
- src/app/modules/login/services/azure.ad.b2c.service.spec.ts
- src/app/modules/reports/components/time-range-custom/time-range-header/time-range-header.component.spec.ts
- src/app/modules/shared/components/details-fields/details-fields.component.spec.ts
- src/app/modules/shared/components/search/search.component.spec.ts
- src/app/modules/shared/components/technologies/technologies.compo …
> Ttl 919 improve testing in UI

- src/app/modules/customer-management/store/customer-management.effects.spec.ts
- src/app/modules/customer-management/store/customer-management.effects.ts
Fix empty message when trying to save a new customer whose name already exist
- src/app/modules/customer-management/store/customer-management.effects.spec.ts
- src/app/modules/customer-management/store/customer-management.effects.ts
- [TTL-836](https://ioetec.atlassian.net/browse/TTL-836)
Message when trying to save a new customer whose name already exist is 'Duplicated'
[TTL-836]: https://ioetec.atlassian.net/browse/TTL-836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: TTL-836 customer duplicated error message

- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
Show a warning when the number of time entries retrieved from the backend reach the limit.
- src/app/modules/time-clock/services/entry.service.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
- src/app/modules/time-clock/store/entry.effects.ts
- [TTL-909](https://ioetec.atlassian.net/browse/TTL-909)
[TTL-909]: https://ioetec.atlassian.net/browse/TTL-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: TTL-909 add warning for max time entries

- src/app/modules/time-entries/pages/time-entries.component.ts
This PR modifies the error message showed when a running time entry is modified and the time in overlaps with another time entry.
src/app/modules/time-entries/pages/time-entries.component.ts
- [TTL-925](https://ioetec.atlassian.net/jira/software/c/projects/TTL/boards/61?modal=detail&selectedIssue=TTL-925)
[TTL-925]: https://ioetec.atlassian.net/browse/TTL-925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: TTL-925 update overlap message

- src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
- src/app/modules/shared/components/technologies/technologies.component.html
- src/app/modules/shared/components/technologies/technologies.component.ts
- src/app/modules/time-clock/store/entry.effects.spec.ts
Tiny changes to some tags and placeholders to improve the front-end UI.
src/app/modules/reports/components/time-entries-table/time-entries-table.component.html
src/app/modules/shared/components/technologies/technologies.component.html
src/app/modules/shared/components/technologies/technologies.component.ts
src/app/modules/time-clock/store/entry.effects.spec.ts
- Add a list of files that have been changed
- [TTL-943](https://ioetec.atlassian.net/jira/software/c/projects/TTL/boards/61?modal=detail&selectedIssue=TTL-943)
[TTL-943]: https://ioetec.atlassian.net/browse/TTL-943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> TTL-943 change title and place holder text

- src/app/modules/shared/components/details-fields/details-fields.component.html
- src/app/modules/shared/components/details-fields/details-fields.component.ts
- src/app/modules/time-clock/components/project-list-hover/project-list-hover.component.ts
- tsconfig.json
Add 3000ms of debounce time to clockin buttons in order to avoid sending multiple times the same request to the backend.
- Add a list of files that have been changed
- [TTL-985](https://ioetec.atlassian.net/browse/TTL-985)
Multiple clockins cannot be sent at the same time 
[TTL-985]: https://ioetec.atlassian.net/browse/TTL-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: TTL-985 add debouncing to clock in buttons
